config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "flights#index"
  resources :flights
  resources :bookings
  resources :users do
    get "my_bookings", on: :member
  end
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: "deprature_airport_id", class_name: "Flight"
  has_many :arriving_flights, foreign_key: "arrival_airport_id", class_name: "Flight"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :user
  has_many :tickets, inverse_of: :booking
  has_many :passengers, through: :tickets, source: :passenger

  accepts_nested_attributes_for :tickets
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings
  has_many :tickets, through: :bookings, source: :tickets
  has_many :passengers, through: :tickets, source: :passenger

  def flight_detail
    "From: #{departure_airport.code} To: #{arrival_airport.code} Departs at: #{start_at.strftime("%H:%M %d/%m/%Y")}"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord  
  has_many :tickets
  has_many :bookings, through: :tickets
  has_many :flights, through: :bookings, source: :flight

  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking

  accepts_nested_attributes_for :passenger
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    if !params[:booking]
      @booking = Booking.new
    else
      @booking = Booking.new(after_search_booking_params)
      @flight = Flight.find(params[:booking][:flight_id])
      @num_passengers = params[:number_of_passengers].to_i
      @num_passengers.times do
        @booking.tickets.build.build_passenger
      end
    end
  end

  def create
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = current_user.bookings.build(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.booking_success(@booking, passenger).deliver_now
      end
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    
    @booking = Booking.find(params[:id])
    if @booking.user != current_user
      redirect_to root_path
    end
  end

  private

  def after_search_booking_params
    params.require(:booking).permit(:flight_id)
  end

  def booking_params
    params.require(:booking).permit(:flight_id, :user_id, tickets_attributes: [passenger_attributes: [:id, :name, :email]])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight = Flight.new
    @airport_options = Airport.all.order(:code).map { |a| [a.code, a.id]}
    @date_options = Flight.where('start_at >= ?', Time.now).pluck(Arel.sql('DISTINCT DATE(start_at) AS date')).sort().map { |date| [date, date] }
    @number_of_seats = 1
    
    if params[:flight]
      @flight_search_results = Flight.where(flight_query_params).where("DATE(start_at) = ?", params[:flight_date] ).order(:start_at).includes([:departure_airport, :arrival_airport])
      @flight = Flight.new(flight_query_params)
      @number_of_seats = params[:number_of_seats]
      @flight_date = params[:flight_date]
      @booking = Booking.new
    end
  end

  private
  def flight_query_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def my_bookings
    @bookings = current_user.bookings
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<% if @flight %>
  <h3>Flight detail<h3>
  <div><%= @flight.flight_detail %></div>
  <%= form_with model: @booking, format: :html do |f| %>
    <div>Passengers Details:</div>
    <%= f.hidden_field :flight_id %>
    <div data-controller="manage-passenger" data-manage-passenger-passenger-number-value="<%= @num_passengers %>" data-manage-passenger-id-value="<%= @num_passengers %>">
      <%= f.fields_for :tickets do |ticket_form| %>
        <div class="passenger-fields">
          <%= ticket_form.fields_for :passenger do |passenger_form| %>
            <br>
            <div>
              <%= passenger_form.label :name %>
              <%= passenger_form.text_field :name %>
            </div>
            <div>
              <%= passenger_form.label :email %>
              <%= passenger_form.text_field :email %>
            </div>
          <% end %>
          <button type="button" data-action="click->manage-passenger#remove">Remove</button>        
        </div>
      <% end %>    
      <template>
        <div class="passenger-fields">
          <br>
          <div>
            <label for="booking_tickets_attributes_2_passenger_attributes_name">Name</label>
            <input type="text" name="booking[tickets_attributes][2][passenger_attributes][name]" id="booking_tickets_attributes_2_passenger_attributes_name">
          </div>
          <div>
            <label for="booking_tickets_attributes_2_passenger_attributes_email">Email</label>
            <input type="text" name="booking[tickets_attributes][2][passenger_attributes][email]" id="booking_tickets_attributes_2_passenger_attributes_email">
          </div>
          <button type="button" data-action="click->manage-passenger#remove">Remove</button>
        </div>
      </template>

      <button type="button" data-action="click->manage-passenger#add" data-manage-passenger-target="addButton">Add Passenger</button>
    </div>
    
    <%= f.submit "Book Flight" %>
  <% end %>
<% end %>

app/views/bookings/show.html.erb
<h3>Booking detail </h3>
<div> Flight detail: <%= @booking.flight.flight_detail %></div> 
<% @booking.passengers.each do |passenger| %>
  <div> Ticket infor: </div>
  <div> Name: <%= passenger.name %></div>    
  <div> Email: <%= passenger.email %></div>  
  <br>  
<% end %>

app/views/flights/_search_form.html.erb
<%= form_with model: @flight, url: flights_path, method: :get do |f| %>
  <h3>Search your flight now</h3>
  <div>
    <%= f.label :departure_airport_id %>
    <%= f.select :departure_airport_id, @airport_options %>
  </div>
  <div>
    <%= f.label :arrival_airport_id %>
    <%= f.select :arrival_airport_id, @airport_options %>
  </div>
  <div>
    <%= label_tag :number_of_seats, "Number of seats" %>
    <%= number_field_tag :number_of_seats, @number_of_seats, min: 1, max: 4  %>
  </div>
  <div>
    <%= label_tag :flight_date %>
    <%= select_tag :flight_date, options_for_select(@date_options, @flight_date) %>
  </div>
  <%= f.submit "Search Flights" %>
<% end %>

app/views/flights/index.html.erb
<%= render "search_form" %>

<% if @flight_search_results && @flight_search_results.size > 0 %>
  <h3>Search Result </h3>
  <%= form_with model: @booking, url: new_booking_path, method: :get do |b| %>
    <%= hidden_field_tag "number_of_passengers", @number_of_seats %>
    <%= b.collection_radio_buttons :flight_id, @flight_search_results, :id, :flight_detail do |bf|%>
      <%= bf.radio_button + bf.label %><br>
    <% end %>  
    <%= submit_tag "Book Flight" %>
  <% end %>
<% else %>
  <% if @flight_search_results && @flight_search_results.size == 0 %>
    <h3>Unfortunately, there are no flight on this day, please try another day! </h3>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "New Search", root_path %>
    <% if user_signed_in? %>   
      <%= link_to "My bookings", my_bookings_user_path(current_user) %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    <hr>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/my_bookings.html.erb
<h3>All of your bookings </h3>

<% @bookings.each do |booking| %>
  <div><%= link_to "Booking:", booking %></div>
  <div> Flight detail: <%= booking.flight.flight_detail %></div> 
  <% booking.passengers.each do |passenger| %>
    <div> Ticket infor: </div>
    <div> Name: <%= passenger.name %></div>    
    <div> Email: <%= passenger.email %></div>  
    <br>  
  <% end %>
  <hr>
<% end %>